/// See from here the pattern problem starts.
/// IN PATTERN PROBLEMS, SPACES TO THE RIGHT ARE SUPPOSED TO BE IGNORED WHILE FINIDING ITS SOLUTION.
/// SPACES TO THE LEFT ARE ONLY TO BE CONSIDERED WHILE FINDING A SOLUTION.
/// IF THERE ARE MULTIPLE CHARACHTERS, BREAK THE PROBLEM INTO THE NUMBER OF DIFFERENT CHRACTERS IT HASAND SOLVE FOR EACH CHARACHTER SEPARATELY.
/// LIKE IF YOU HAVE STARS AND SPACES( ANYWHERE APART FROM RIGHT ), YOU WILL HAVE TO COME UP WITH 2 DIFFERENT LOGICS FOR SPACES AND STAR'S COLUMN PART ONLY, THE ROW LOGIC OF BOTH WILL BE ONE ONLY.
/// THEN THE PATTERN NEEDS TO BE BROKEN INTO ROWS, COLUMNS AND THE PRINTED CHARACTER -
/// a) THE FIRST FOR LOOP IS FOR ROWS ie. THE NUMBER OF ROWS THATS NEEDS TO BE PRINTED
/// b) THE SECOND FOR LOOP IS FOR COLUMNS ie. THE NUMBER OF COLUMNS EACH ROW SHOULD HAVE
/// c) THEN AT LAST YOU HAVE TO PRINT WHHICH CHARACTER/VALUE NEEDS TO BE PRINTED. EITHER YOU WILL HAVE TO MANIPULATE THE VALUE OR DIRECTLY PRINT THE CHARACTER REQUIRED DIRECTLY.

//#include<bits/stdc++.h>
//using namespace std;

//int main()
//{
//    int rows;
//    cin >> rows;

//    for( int i = 1; i <= rows; i++ )// THE FIRST FOR LOOP IS FOR ROWS ie. THE NUMBER OF ROWS THATS NEEDS TO BE PRINTED
//    {
//        for( int j = 1 ; j <= i; j++ )//THE SECOND FOR LOOP IS FOR COLUMNS ie. THE NUMBER OF COLUMNS EACH ROW SHOULD HAVE
//        {
//            cout << i + j - 1 << " "; // THEN AT LAST YOU HAVE TO PRINT WHHICH CHARACTER/VALUE NEEDS TO BE PRINTED. EITHER YOU WILL HAVE TO MANIPULATE THE VALUE OR DIRECTLY PRINT THE CHARACTER REQUIRED DIRECTLY.
//        }
//        cout << endl;
//    }
//    return 0;
//}

#include<iostream>
using namespace std;

int main(){
    int rows,num;
    //cout << "Enter the number of rows" << endl;
    cin >> rows;
    for( int i = 1; i <= rows; i++ ){
        num = i;
        for( int j = 1; j<= i; j++,num++ ){
            cout << num;
        }
        cout << endl;
    }
    return 0;
}
